[tool.black]
line-length = 120
target-version = ['py37']
skip-string-normalization = false
exclude = '''
(
  /(
    | \.git
    | node_modules
  )/
)
'''

[tool.isort]
line_length = 120
multi_line_output = 5
balanced_wrapping = true
known_django = 'django'
sections = 'FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER'
skip = 'node_modules'


[tool.mypy]
# The mypy configurations: https://mypy.readthedocs.io/en/latest/config_file.html
python_version = "3.10"
check_untyped_defs = true
disallow_any_generics = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
ignore_errors = false
ignore_missing_imports = true
implicit_reexport = false
strict_optional = true
strict_equality = true
no_implicit_optional = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unreachable = true
warn_no_return = true

plugins = [
  "mypy_django_plugin.main",
  "mypy_drf_plugin.main"
]

[tool.django-stubs]
django_settings_module = "config.settings"
